CREATE DATABASE banco01
GO

USE banco01
GO

CREATE TABLE teste(
	nome VARCHAR(30)
)
GO

/*
 ORGANIZAR FISICAMENTE E LOGICAMENTE UM BANCO DE DADOS 

1 - CRIAR O BANCO COM ARQUIVOS PARA OS SETORES DE MKT E VENDAS;
2 - CRIAR UM ARQUIVO GERAL;
3 - DEIXAR O MDF APENAS COM O DICIONÁRIO DE DADOS;
4 - CRIAR OS GRUPOS DE ARQUIVOS (PRIMARY - MDF).
*/

CREATE TABLE TB_EMPRESA(
	ID INT,
	NOME VARCHAR(50)
)
GO

/* CONECTANDO A UM BANCO DE DADOS */

USE EMPRESA
GO

/* CRIANDO TABELAS */

CREATE TABLE ALUNO(
	IDALUNO INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(50) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	NASCIMENTE DATE NOT NULL,
	EMAIL VARCHAR(50) UNIQUE NOT NULL
)
GO

/* CONSTRAINTS */

ALTER TABLE ALUNO
ADD CONSTRAINT CK_SEXO CHECK (SEXO IN('M','F'))
GO

/* 1 X 1 */

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY(100,10),
	BAIRRRO VARCHAR(30) NOT NULL,
	UF CHAR(2) NOT NULL
	CHECK(UF IN('RJ','SP','MG')),
	ID_ALUNO INT UNIQUE NOT NULL
)
GO

/* 1 X N */
CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY IDENTITY(1,1),
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_ALUNO INT NOT NULL,
	CHECK (TIPO IN ('RES','COM','CEL'))
)
GO

/* CRIANDO A FK */

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY(ID_ALUNO) REFERENCES ALUNO(IDALUNO)
GO

/* COMANDOS DE DESCRIÇÃO */

/* PROCEDURES - JÁ CRIADAS E ARMAZENADAS NO SISTEMA */

SP_COLUMNS ALUNO
GO

SP_HELP ALUNO
GO

/* INSERINDO DADOS */

INSERT INTO ALUNO VALUES('ANDRE','M','1981/12/09','ANDRE@EMAIL.COM')
INSERT INTO ALUNO VALUES('ANA','F','1989/11/17','ANA@EMAIL.COM')
INSERT INTO ALUNO VALUES('RUI','M','2004/03/11','RUI@EMAIL.COM')
INSERT INTO ALUNO VALUES('JOAO','M','1976/07/23','JOAO@EMAIL.COM')
GO

SELECT * FROM ALUNO
GO

/* ENDERECO */
INSERT INTO ENDERECO VALUES('FLAMENGO','RJ',1)
INSERT INTO ENDERECO VALUES('MORUMBI','SP',2)
INSERT INTO ENDERECO VALUES('CENTRO','SP',3)
INSERT INTO ENDERECO VALUES('CENTRO','MG',4)
GO

SELECT * FROM ENDERECO 
ORDER BY ID_ALUNO
GO

/* TELEFONE */

INSERT INTO TELEFONE VALUES('CEL','7776632',1)
INSERT INTO TELEFONE VALUES('RES','8823232',1)
INSERT INTO TELEFONE VALUES('COM','2233228',2)
INSERT INTO TELEFONE VALUES('CEL','8982234',2)
GO

SELECT * FROM TELEFONE
GO

/* PEGAR DATA ATUAL DO SISTEMA */

SELECT GETDATE()
GO

/* CLAUSULA AMBIGUA */
SELECT 
	A.NOME, 
	T.TIPO, 
	T.NUMERO, 
	E.BAIRRRO, E.UF
FROM ALUNO A
LEFT JOIN TELEFONE T
ON A.IDALUNO = T.ID_ALUNO
LEFT JOIN ENDERECO E
ON A.IDALUNO = E.ID_ALUNO
GO